//created on: 26/04/2017
package green

declare Alumno
    nombre : String @key
    materia : Materia[] @key
    matricula : String @key
    carrera: String @key
end 
declare Materia
    nombre : String @key
    desempenio : Desempenio @key
end 

declare Desempenio
    tema : String @key
    tareas : Tarea @key
    ejercicioEnClase : EjeEnClase @key
    examen : Examen @key
end

declare Tarea
    id : int @key
    calificacion : int @key
    parcial : int @key
end
declare EjeEnClase
    id : int @key
    calificacion : int @key
    parcial : int @key
end
declare Examen
    id : int @key
    calificacion : int@key
    parcial : int @key
end
rule "Carga hechos"
     when
     
     then
    EjeEnClase eje = new EjeEnClase(1, 90, 1); 
    insert(eje);
    eje = new EjeEnClase(2, 95, 1); 
    insert(eje);  
    Tarea tar = new Tarea(1, 68, 1);
    insert(tar);  
    tar = new Tarea(2, 50, 1);
    insert(tar);
    Examen ex = new Examen(1, 70, 1);
    insert(ex);
    //
    EjeEnClase eje2 = new EjeEnClase(1, 100, 1); 
    insert(eje2);
    eje2 = new EjeEnClase(2, 95, 1); 
    insert(eje2);  
    Tarea tar2 = new Tarea(1, 100, 1);
    insert(tar2);  
    tar2 = new Tarea(2,60, 1);
    insert(tar2);
    Examen ex2 = new Examen(1, 100, 1);
    insert(ex2);
    
    Desempenio des = new Desempenio("Erlang",tar,eje,ex);
    insert(des); 
    Desempenio des2 = new Desempenio("Drools",tar2,eje2,ex2);
    insert(des2); 
    Materia[] mat = new Materia[2];
    mat[0]= new Materia("Erlang", des);
    mat[1] = new Materia("Drools", des2); 
    insert(mat);
    Alumno al = new Alumno("Alan Herrera",mat,"A01338336","ITC");
    insert(al);
    
end

rule "Desempeño tareas"
     when
      //&& $a11.materia.desempenio.tareas.calificacion < 70
    $al1 : Alumno()
    
    //$al2 : Alumno($al1.materia.desempenio.tareas.calificacion <70)
    
     then
     for(int i = 0; i < $al1.getMateria().length; i++){
        if($al1.getMateria()[i].getDesempenio().getTareas().getCalificacion() < 70){
            System.out.println($al1.getNombre()+ " saliste muy bajo en tareas , te recomendamos que leas contenidos para principiantes sobre "+ $al1.getMateria()[i].getDesempenio().getTema());
        }else{
            if($al1.getMateria()[i].getDesempenio().getTareas().getCalificacion() > 70 && $al1.getMateria()[i].getDesempenio().getTareas().getCalificacion() < 85 ){
            System.out.println($al1.getNombre()+ " te recomendamos que leas contenidos intermedios sobre "+ $al1.getMateria()[i].getDesempenio().getTema());
            }else{
                System.out.println($al1.getNombre()+ " vas muy bien en tareas, si quieres aprender más puedes leer contenidos avanzados sobre "+ $al1.getMateria()[i].getDesempenio().getTema());
            }
         }
    }
end

rule "Desempeño ejercicios"
     when
    $al1 : Alumno()
    
     then
        for(int i = 0; i < $al1.getMateria().length; i ++){
            if($al1.getMateria()[i].getDesempenio().getEjercicioEnClase().getCalificacion() < 70){
                System.out.println($al1.getNombre()+ " saliste muy bajo en los ejercicios, te recomendamos que hagas ejercicios para principiantes sobre "+ $al1.getMateria()[i].getDesempenio().getTema());
            }else{
                if($al1.getMateria()[i].getDesempenio().getEjercicioEnClase().getCalificacion() > 70 && $al1.getMateria()[i].getDesempenio().getEjercicioEnClase().getCalificacion() < 85 ){
                System.out.println($al1.getNombre()+ " te recomendamos hacer ejercicios intermedios sobre "+ $al1.getMateria()[i].getDesempenio().getTema());
                }else{
                    System.out.println($al1.getNombre()+ " vas muy bien en ejericios, si quieres aprender más puedes hacer ejercicios avanzados sobre "+ $al1.getMateria()[i].getDesempenio().getTema());
                }
            }
         }
end

rule "Parcial 1"
    when 
    $al : Alumno()
    
    $ex : Alumno($al.materia[0].desempenio.examen.parcial == 1 && $ex.materia == $al.materia)

    $totalTar : Double() from accumulate(
         Tarea( parcial == 1, $tar : calificacion ),
         average( $tar ) )
         
    $totalEj : Double() from accumulate(
         EjeEnClase( parcial == 1, $ej : calificacion ),
         average( $ej ) )
    then
    
    for(int i = 0; i < $al.getMateria().length; i++){
        double parcial1 = ($ex.getMateria()[i].getDesempenio().getExamen().getCalificacion()*.60)+($totalEj*.20)+($totalTar*.20);
        if(parcial1 <70){
            System.out.println("Necesitas repasar más del tema " + $al.getMateria()[i].getDesempenio().getTema()+ " para obtener una mejor calificación parcial");
        }
        else if(parcial1>70 && parcial1<85){
            System.out.println("Te recomendamos un pequeño repaso de  " + $al.getMateria()[i].getDesempenio().getTema() + " por tu desempeño en el parcial 1 ");
        }
        else{
            System.out.println("Te fue muy bien en el primer parcial de " + $ex.getMateria()[i].getNombre() + ", sigue así");
        }
        System.out.println($al.getNombre() +" tu calificacion del parcial 1 es de "+ (($ex.getMateria()[i].getDesempenio().getExamen().getCalificacion()*.60)+($totalEj*.20)+($totalTar*.20))+" en la materia "+ $ex.getMateria()[i].getDesempenio().getTema());
    }
end

rule "Parcial 2"
    when 
    $al : Alumno()
    $ex : Alumno($al.materia[0].desempenio.examen.parcial == 2)

    $totalTar : Double() from accumulate(
         Tarea( parcial ==2, $tar : calificacion ),
         average( $tar ) )
         
    $totalEj : Double() from accumulate(
         EjeEnClase( parcial ==2, $ej : calificacion ),
         average( $ej ) )
    then
    for(int i = 0; i < $al.getMateria().length; i++){
        double parcial2 = ($ex.getMateria()[i].getDesempenio().getExamen().getCalificacion()*.60)+($totalEj*.20)+($totalTar*.20);
        if(parcial2<70){
            System.out.println("Necesitas repasar más del tema " + $al.getMateria()[i].getDesempenio().getTema());
        }
        else if(parcial2>70 && parcial2<85){
            System.out.println("Te recomendamos un pequeño repaso de  " + $al.getMateria()[i].getDesempenio().getTema() + " por tu desempenño en el parcial 1 ");
        }
        else{
            System.out.println("Te fue muy bien en el segundo parcial de" + $ex.getMateria()[i].getNombre() + ", sigue así");
        }
        System.out.println($al.getNombre() +" tienes un promedio de "+ (($ex.getMateria()[i].getDesempenio().getExamen().getCalificacion()*.60)+($totalEj*.20)+($totalTar*.20)) + " en el parcial 2");
    }
end 
